---
# Default behavior and action
backup_action: "enable_backup_protection"
backup_actions:
  - enable_backup_protection


# Paths
# Default logs directory - always relative to repo root
logs_dir: ansible/logs
