---
galaxy_info:
  author: dteenergy
  description: Azure role to install Dynatrace OneAgent and manage alerting profiles
  company: DTE Energy
  license: Apache-2.0
  min_ansible_version: 2.10
dependencies: []
