---
# Main tasks file for common role
# This file can be used to include other common tasks

- name: Include manifest loading tasks
  ansible.builtin.include_tasks: load_manifest.yml
  when: load_manifest | default(false)

- name: Migrate on-prem SQL to SQLMI using DMS
  ansible.builtin.include_tasks: migrate_sql_to_sqlmi_dms.yml
  when: migrate_sql_to_sqlmi_dms | default(false)
