---
# TODO: to be tested later, will go through testing against actual VMs
- name: Replicate SQL DB to Azure SQL Database using Azure DMS
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    verify_azure_account: true
  roles:
    - role: common
    - role: replicate_sqldb
      vars:
        manifest: "{{ manifest }}"
        dry_run: "{{ dry_run }}"
