name: Create Release from Alpha Tag

on:
  push:
    tags:
      - 'v*.*.*-alpha.*'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: dteenergy/cloud-platform-github-actions/bump-version/create-release@main
        id: release
        with:
          app-id: ${{ secrets.CLOUD_PLATFORM_GITHUB_ACTION_APP_ID }}
          private-key: ${{ secrets.CLOUD_PLATFORM_GITHUB_ACTION_PRIVATE_KEY }}
          github-ref: ${{ github.ref_name }}

      - uses: dteenergy/cloud-platform-github-actions/bump-version/cleanup@main
        with:
          app-id: ${{ secrets.CLOUD_PLATFORM_GITHUB_ACTION_APP_ID }}
          private-key: ${{ secrets.CLOUD_PLATFORM_GITHUB_ACTION_PRIVATE_KEY }}
          release-tag: ${{ steps.release.outputs.release-tag }}
          terraform-token: ${{ secrets.TF_TOKEN }}
